var path = require('path');
var webpack = require('webpack');
module.exports = {
	entry: {
		index:'./entry/index',
		address:'./entry/address',
		"authorize-login":'./entry/authorize-login',
		"bank-card-delet":'./entry/bank-card-delet',
		"bank-card-list":'./entry/bank-card-list',
		"bind-bank-card":'./entry/bind-bank-card',
		"findpsw":'./entry/findpsw',
		"index-boss":'./entry/index-boss',
		"index-boss-bycz":'./entry/index-boss-bycz',
		"index-boss-bysy":'./entry/index-boss-bysy',
		"index-boss-bysy-detail":'./entry/index-boss-bysy-detail',
		"index-boss-fxyj":'./entry/index-boss-fxyj',
		"index-boss-kqjl":'./entry/index-boss-kqjl',
		"index-boss-kyye":'./entry/index-boss-kyye',
//		"index-boss-qyygcb":'./entry/index-boss-qyygcb',
//		"index-boss-qyygcb-detail":'./entry/index-boss-qyygcb-detail',
		"index-boss-rgcb":'./entry/index-boss-rgcb',
		"index-boss-rgcb-item":'./entry/index-boss-rgcb-item',
		"index-boss-rgcb-list":'./entry/index-boss-rgcb-list',
		"index-boss-rgcb-list-detail":'./entry/index-boss-rgcb-list-detail',
		"index-boss-spgl":'./entry/index-boss-spgl',
//		"index-boss-yghmc":'./entry/index-boss-yghmc',
//		"index-boss-yghmc-detail":'./entry/index-boss-yghmc-detail',
		"index-boss-ygjq":'./entry/index-boss-ygjq',
//		"index-boss-ygkq-detail":'./entry/index-boss-ygkq-detail',
		"index-boss-ygtj":'./entry/index-boss-ygtj',		
		"index-bumen-ygkq-detail":'./entry/index-bumen-ygkq-detail',
		jqcx:'./entry/jqcx',
		jqsp:'./entry/jqsp',
		jqsq:'./entry/jqsq',
//		"jqsp-bmld":'./entry/jqsp-bmld',
		"jqsq-userlist":'./entry/jqsq-userlist',
		"jqsq-userlist-shen-he-ren":'./entry/jqsq-userlist-shen-he-ren',
		kqjl:'./entry/kqjl',		
		"kqjl-bumen":'./entry/kqjl-bumen',
		"li-ji-ru-zhi":'./entry/li-ji-ru-zhi',
		"login":'./entry/login',
		"qiye-zhuce-step01":'./entry/qiye-zhuce-step01',
		"qiye-zhuce-step02":'./entry/qiye-zhuce-step02',
		"register":'./entry/register',
		"resetpsw":'./entry/resetpsw',
//		rsgl:'./entry/rsgl',
//		"rsgl-fxyj":'./entry/rsgl-fxyj',
//		"rsgl-rlzsh":'./entry/rsgl-rlzsh',
//		"rsgl-ygkq-kqjl":'./entry/rsgl-ygkq-kqjl',
		"ruzhi-wdll-grzl":'./entry/ruzhi-wdll-grzl',	
		"ruzhi-wdll-grzl-add":'./entry/ruzhi-wdll-grzl-add',
		"ruzhi-wdll-grzl-add-birthday":'./entry/ruzhi-wdll-grzl-add-birthday',
		"ruzhi-wdll-gzjl":'./entry/ruzhi-wdll-gzjl',
		"ruzhi-wdll-gzjl-add":'./entry/ruzhi-wdll-gzjl-add',
		"ruzhi-wdll-jtbj":'./entry/ruzhi-wdll-jtbj',
		"ruzhi-wdll-jtbj-add":'./entry/ruzhi-wdll-jtbj-add',
		
		"ruzhi-wdll-jyjl":'./entry/ruzhi-wdll-jyjl',
		"ruzhi-wdll-jyjl-add":'./entry/ruzhi-wdll-jyjl-add',
		"score-dzjf":'./entry/score-dzjf',		
		"score-tixian":'./entry/score-tixian',
		"score-xjgz":'./entry/score-xjgz',
		"score-zsjf":'./entry/score-zsjf',
		"select-bank-card":'./entry/select-bank-card',
		setting:'./entry/setting',
		"setting-gonggao":'./entry/setting-gonggao',
		"setting-gonggao-detail":'./entry/setting-gonggao-detail',
		"setting-gywm":'./entry/setting-gywm',
		"setting-gzzd":'./entry/setting-gzzd',
		"setting-gzzd-detail":'./entry/setting-gzzd-detail',
		"setting-lzxx":'./entry/setting-lzxx',
		"setting-shezhi":'./entry/setting-shezhi',
		"setting-shezhi-dlmmxg":'./entry/setting-shezhi-dlmmxg',
		"setting-shezhi-zfmmxg":'./entry/setting-shezhi-zfmmxg',
		"setting-wdll-grzl":'./entry/setting-wdll-grzl',
//		"setting-wdll-grzl-add":'./entry/setting-wdll-grzl-add',
//		"setting-wdll-gzjl":'./entry/setting-wdll-gzjl',
//		"setting-wdll-gzjl-add":'./entry/setting-wdll-gzjl-add',
//		"setting-wdll-jyjl":'./entry/setting-wdll-jyjl',
//		"setting-wdll-jyjl-add":'./entry/setting-wdll-jyjl-add',
		"setting-yjfk":'./entry/setting-yjfk',
		"setting-zwxx":'./entry/setting-zwxx',
//		"zhongda-chongzhi":'./entry/zhongda-chongzhi',
		"select-tongshi":'./entry/select-tongshi',
		"ruzhi-wdll-zwpj":'./entry/ruzhi-wdll-zwpj',		
		"score-xjgz-mingxi":'./entry/score-xjgz-mingxi',
		"score-jifen-mingxi":'./entry/score-jifen-mingxi',
//		"zhongda-chongzhi-boss":'./entry/zhongda-chongzhi-boss',
		"index-boss-kyjf":'./entry/index-boss-kyjf',
		"zhuanzhang-tongshi-boss":'./entry/zhuanzhang-tongshi-boss',
		"zhuanzhang-tongshi":'./entry/zhuanzhang-tongshi'
		
		
	},	
	output:{
		path:path.resolve(__dirname, 'buildNew'),
		filename: "[name].js"
	},
	
	resolve: {	
        extensions: [ '.js'],       
    }
}
